"""
Validate a generated review CSV on two fronts.

1. INSTRUCTION COMPLIANCE -- did each review obey the 16-cell factorial instruction it
   was actually given? The requested aspects and few-shot examples are not stored in the
   CSV, so they are recovered by replaying the generator's seeded RNG: the same
   `random.Random(f"{seed}:{cell_id}")` stream, the same hotel rotation, the same calls
   into `build_messages`. This imports the generator rather than reimplementing it, so
   the replay cannot drift from what actually ran.

2. STYLOMETRY vs the human corpus -- does the generated text carry giveaways that would
   let a classifier separate the LLM class for reasons unrelated to the study question?
   Every metric is reported LLM / real / human-fake side by side, because "66% start with
   I" only means something next to the 21% the real corpus does.

   The perfect-separator check is deliberately generic: it looks for ANY character
   appearing in the LLM output but effectively absent from both human classes, so the
   next artifact is caught without anyone knowing to look for it. That check exists
   because the en-dash slipped through once already, at 14.6% of LLM reviews against
   0.0% of 1592 human ones, caused by em-dashes in the prompt file itself.

Usage:
    python3 src/validate_generated.py                      # default output CSV
    python3 src/validate_generated.py --generated <csv>
    python3 src/validate_generated.py --no-judge           # skip the LLM sentiment judge
"""

import argparse
import itertools
import json
import random
import re
import sys
from collections import Counter
from pathlib import Path

import pandas as pd
import requests

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as cfg
from generate_synthetic_reviews import ALL_CELLS, ExamplePool, build_messages, length_band


# ---------------------------------------------------------------------------
# Aspect detection
# ---------------------------------------------------------------------------
# Keyword regexes, so this UNDERCOUNTS: a review conveying noise as "I could hear every
# footstep upstairs" scores as a miss. Treat coverage as a lower bound, and read the
# structured-vs-unstructured gap rather than the absolute number.

ASPECT_PATTERNS = {
    "the location": r"\b(?:locat|neighborhood|nearby|walk(?:ing)?\s+distance|block[s]?\s+from|downtown|close to|around the corner|steps from)",
    "the price / value for money": r"\b(?:price[ds]?|pricing|cost|rate[s]?|value|expensive|cheap|afford|worth (?:it|the)|for what (?:we|i) paid|bargain|overpriced)",
    "room cleanliness": r"\b(?:clean|dirt(?:y|ier)|spotless|stain|dust|grime|hygien|immaculate|filth|housekeeping|tidy)",
    "how long the stay was": r"\b(?:\d+\s*(?:night|day|week)|one night|two nights|three nights|a week|weekend|stayed for|our stay|overnight)",
    "the staff": r"\b(?:staff|reception|front desk|concierge|manager|employee|housekeep|bellhop|porter|check[- ]?in)",
    "noise levels": r"\b(?:nois(?:e|y)|quiet|loud|sound(?:proof)?|hear(?:d|ing)?\s|thin walls|traffic outside|silent|peaceful)",
    "breakfast": r"\b(?:breakfast|buffet|continental|morning meal|coffee (?:bar|station)|omelet|pastri)",
}

PREAMBLE_LEAK = r"^\s*(?:sure|certainly|of course|here(?:'s| is)|review\s*:)"
AI_DISCLOSURE = r"\b(?:as an ai|language model|i cannot|i'm unable to|generated by)"


def opener_word(text: str) -> str:
    m = re.match(r"[^A-Za-z]*([A-Za-z']+)", str(text))
    return m.group(1).lower() if m else ""


def ngram_overlap(a: str, b: str, n: int = 6) -> int:
    """Longest run of n-grams from `b` that appears verbatim in `a`. Detects few-shot
    copying, which would make the few_shot cells parrots rather than a real condition."""
    aw, bw = str(a).lower().split(), str(b).lower().split()
    if len(bw) < n or len(aw) < n:
        return 0
    agrams = {" ".join(aw[i:i + n]) for i in range(len(aw) - n + 1)}
    return sum(1 for i in range(len(bw) - n + 1) if " ".join(bw[i:i + n]) in agrams)


# ---------------------------------------------------------------------------
# RNG replay
# ---------------------------------------------------------------------------

def reconstruct_instructions(gen: pd.DataFrame, examples_csv: Path, tolerance: float):
    """Recover the exact aspects / few-shot examples / opener each row was asked for.

    Replays the generator's per-cell RNG. Requires the run to have used a single seed and
    a contiguous rep_index range -- both true of any run the generator produced.
    """
    pool = ExamplePool(examples_csv)
    targets = {k: dict(v) for k, v in cfg.LENGTH_TARGETS.items()}
    combo_ordinal = {c: i for i, c in enumerate(ALL_CELLS)}

    # The replay reproduces the CURRENT prompt code. A CSV written before the opener draw
    # was added has an RNG stream offset by one call per review, so recovered aspects and
    # examples are wrong for every rep after the first. Stylometry does not depend on the
    # replay and stays valid either way.
    if "opener_move" not in gen.columns:
        print("\n  ! This CSV predates opener steering. The RNG stream has since changed,")
        print("    so sections 3 and 4 (structure, example_mode) are NOT valid for it.")
        print("    Sections 1, 6, 7, 8 are unaffected.")

    seeds = gen["gen_seed"].unique()
    if len(seeds) != 1:
        print(f"  ! multiple seeds {list(seeds)} in one file; replay skipped")
        return {}
    seed = int(seeds[0])
    n_per_cell = int(gen["rep_index"].max()) + 1

    recovered = {}
    for (length, sentiment, structure, example_mode) in ALL_CELLS:
        cell_id = f"{length}_{sentiment}_{structure}_{example_mode}"
        rng = random.Random(f"{seed}:{cell_id}")
        for rep in range(n_per_cell):
            ordinal = combo_ordinal[(length, sentiment, structure, example_mode)] \
                * n_per_cell + rep
            hotel = pool.hotels[ordinal % len(pool.hotels)]
            messages, opener_move = build_messages(
                length, sentiment, structure, example_mode, hotel, pool, targets, rng,
                tolerance,
            )
            sysmsg = messages[0]["content"]
            aspects = []
            m = re.search(r"\(no bullet points, no headings\): (.+?)\.\n", sysmsg)
            if m:
                aspects = [a.strip() for a in m.group(1).split(",")]
            recovered[(cell_id, rep)] = {
                "hotel": hotel,
                "aspects": aspects,
                "opener_move": opener_move,
                "user_msg": messages[1]["content"],
            }
    return recovered


# ---------------------------------------------------------------------------
# LLM sentiment judge
# ---------------------------------------------------------------------------

def judge_sentiment_llm(texts, url, model):
    """Ask the model to classify sentiment.

    Primary over a word-count lexicon on purpose: on the llama3.2 sample the lexicon
    scored negative reviews at 45.8% while the judge scored 100%, because mixed-tone
    reviews ("the bed was comfortable, but the AC rattled all night") tip positive on raw
    counts. The lexicon was the broken instrument, not the data.
    """
    out = []
    for t in texts:
        try:
            r = requests.post(
                url,
                json={
                    "model": model,
                    "messages": [
                        {"role": "system", "content":
                         "Classify the overall sentiment of the hotel review as exactly "
                         "one word: positive or negative. Output only that word."},
                        {"role": "user", "content": str(t)},
                    ],
                    "stream": False,
                    "options": {"temperature": 0},
                },
                timeout=cfg.REQUEST_TIMEOUT,
            )
            r.raise_for_status()
            v = r.json()["message"]["content"].strip().lower()
            out.append("positive" if "positive" in v else
                       "negative" if "negative" in v else "unknown")
        except Exception as e:
            out.append(f"error:{type(e).__name__}")
    return out


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

def section(title):
    print(f"\n{'=' * 78}\n{title}\n{'=' * 78}")


def report_length(gen, tolerance):
    section("1. LENGTH")
    for name, g in gen.groupby("length"):
        lo, hi = length_band(cfg.LENGTH_TARGETS[name]["chars"], tolerance)
        print(f"  {name:6s} n={len(g):3d}  target={cfg.LENGTH_TARGETS[name]['chars']:4d} "
              f"band={lo}-{hi}  mean={g.n_chars.mean():7.1f}  "
              f"in-band={100 * g.in_length_band.mean():5.1f}%  "
              f"attempts={g.n_attempts.mean():.2f}")


def report_sentiment(gen, url, model, use_judge):
    section("2. SENTIMENT")
    if not use_judge:
        print("  (skipped: --no-judge)")
        return
    verdict = judge_sentiment_llm(gen.text.tolist(), url, model)
    gen = gen.assign(judged=verdict)
    for name, g in gen.groupby("sentiment"):
        ok = (g.judged == name).sum()
        print(f"  requested {name:8s} n={len(g):3d}  judge agrees {ok:3d} "
              f"({100 * ok / len(g):5.1f}%)")
    bad = gen[gen.judged.str.startswith("error")]
    if len(bad):
        print(f"  ! {len(bad)} judge calls errored")


def report_structure(gen, recovered):
    section("3. STRUCTURE (aspect coverage)")
    print("  Regex keyword matching, so these are LOWER BOUNDS. Read the structured-vs-")
    print("  unstructured gap, not the absolute rate.\n")

    rows = []
    for _, r in gen.iterrows():
        info = recovered.get((r.cell_id, r.rep_index))
        if not info or not info["aspects"]:
            continue
        hits = sum(
            1 for a in info["aspects"]
            if a in ASPECT_PATTERNS and re.search(ASPECT_PATTERNS[a], str(r.text), re.I)
        )
        rows.append({"length": r.length, "asked": len(info["aspects"]), "hit": hits})
    if not rows:
        print("  (no structured rows recovered)")
        return
    d = pd.DataFrame(rows)
    tot_a, tot_h = d.asked.sum(), d.hit.sum()
    print(f"  structured overall: {tot_h}/{tot_a} named aspects covered "
          f"({100 * tot_h / tot_a:.1f}%)")
    for L, g in d.groupby("length"):
        print(f"    {L:6s}: {g.hit.sum()}/{g.asked.sum()} "
              f"({100 * g.hit.sum() / g.asked.sum():5.1f}%)")
    print("\n  Short cells are expected to lag: ASPECTS_PER_REVIEW=%d will not fit in "
          "%d chars." % (cfg.ASPECTS_PER_REVIEW, cfg.LENGTH_TARGETS['short']['chars']))

    # Free-mention rate across ALL reviews, to show whether the manipulation bites at all.
    print("\n  Aspects mentioned per review (any aspect, structured vs not):")
    for S, g in gen.groupby("structure"):
        n = g.text.map(lambda t: sum(
            1 for p in ASPECT_PATTERNS.values() if re.search(p, str(t), re.I))).mean()
        print(f"    {S:12s}: {n:.2f} / {len(ASPECT_PATTERNS)}")


def report_example_mode(gen, recovered):
    section("4. EXAMPLE MODE (few-shot copying)")
    worst, n_any, n_fs = 0, 0, 0
    for _, r in gen.iterrows():
        if r.example_mode != "few_shot":
            continue
        info = recovered.get((r.cell_id, r.rep_index))
        if not info:
            continue
        n_fs += 1
        c = ngram_overlap(info["user_msg"], r.text, n=6)
        worst = max(worst, c)
        n_any += c > 0
    print(f"  few-shot rows reconstructed: {n_fs}")
    print(f"  reviews with any copied 6-gram: {n_any}   max copied 6-grams: {worst}")
    if worst > 5:
        print("  ! substantial copying: the few_shot cells may be parroting examples")


def report_opener(gen, recovered):
    section("5. OPENER COMPLIANCE")
    if "opener_move" not in gen.columns:
        print("  (no opener_move column: CSV predates opener steering)")
        return
    fw = gen.text.map(opener_word)
    first_person_sg = fw.isin(["i", "i'm", "i've", "id", "my"])
    first_person_pl = fw.isin(["we", "we've", "our", "us"])
    for mv, g in gen.groupby("opener_move"):
        sub_fw = g.text.map(opener_word)
        if mv.startswith("first person singular"):
            ok = sub_fw.isin(["i", "i'm", "i've", "my"]).mean()
        elif mv.startswith("first person plural"):
            ok = sub_fw.isin(["we", "we've", "our", "us"]).mean()
        else:
            # For the open-ended moves, the check is only that it did NOT fall back to
            # the default first-person opener.
            ok = 1 - sub_fw.isin(["i", "i'm", "i've", "we", "my", "our"]).mean()
        label = "opens as asked" if mv.startswith("first person") else "avoided I/We default"
        print(f"  {mv[:52]:54s} n={len(g):3d}  {label}: {100 * ok:5.1f}%")


def report_stylometry(gen, hum):
    section("6. STYLOMETRY vs HUMAN CORPUS")
    real = hum[hum.Binary_label == cfg.REAL_LABEL].text.astype(str)
    fake = hum[hum.Binary_label == cfg.FAKE_LABEL].text.astype(str)
    llm = gen.text.astype(str)
    sets = [("LLM", llm), ("real", real), ("human-fake", fake)]

    print(f"  {'metric':32s} {'LLM':>10s} {'real':>10s} {'human-fake':>12s}")
    print("  " + "-" * 68)

    def row(name, fn):
        vals = [fn(s) for _, s in sets]
        print(f"  {name:32s} {vals[0]:9.1f}% {vals[1]:9.1f}% {vals[2]:11.1f}%")

    row("starts with 'I'", lambda s: 100 * s.map(opener_word).eq("i").mean())
    row("starts with I/We/My/Our",
        lambda s: 100 * s.map(opener_word).isin(["i", "we", "my", "our"]).mean())
    row("contains em-dash —", lambda s: 100 * s.str.contains("—").mean())
    row("contains en-dash –", lambda s: 100 * s.str.contains("–").mean())
    row("contains spaced hyphen ' - '", lambda s: 100 * s.str.contains(" - ").mean())
    row("contains any hyphen", lambda s: 100 * s.str.contains("-").mean())
    row("contains semicolon", lambda s: 100 * s.str.contains(";").mean())

    # Opener diversity, bootstrapped to the LLM sample size so the numbers are comparable.
    n = len(llm)
    boots = [real.sample(n, random_state=i).map(opener_word).nunique() for i in range(200)]
    lo, hi = pd.Series(boots).quantile([0.025, 0.975])
    got = llm.map(opener_word).nunique()
    flag = "OK" if lo <= got <= hi else "OUTSIDE real-corpus range"
    print(f"\n  distinct openers in {n} reviews: LLM={got}  "
          f"real 95% range={lo:.0f}-{hi:.0f}   -> {flag}")
    print("  LLM top openers:", Counter(llm.map(opener_word)).most_common(6))


def report_perfect_separators(gen, hum):
    section("7. PERFECT SEPARATORS (generic artifact scan)")
    print("  Any character common in LLM output but effectively absent from BOTH human")
    print("  classes is a free label for a classifier. This scan is deliberately generic:")
    print("  the en-dash slipped through once already because nobody was looking for it.\n")

    llm = gen.text.astype(str)
    real = hum[hum.Binary_label == cfg.REAL_LABEL].text.astype(str)
    fake = hum[hum.Binary_label == cfg.FAKE_LABEL].text.astype(str)

    chars = {c for t in llm for c in t if not c.isalnum() and not c.isspace()}
    flagged = []
    for c in sorted(chars):
        lr = llm.str.contains(re.escape(c)).mean()
        rr = real.str.contains(re.escape(c)).mean()
        fr = fake.str.contains(re.escape(c)).mean()
        if lr > 0.01 and rr < 0.001 and fr < 0.001:
            flagged.append((c, lr, rr, fr))

    if not flagged:
        print("  PASS: no character separates the LLM class outright.")
    else:
        print("  FAIL: these characters are near-perfect giveaways --")
        for c, lr, rr, fr in flagged:
            print(f"    {c!r} (U+{ord(c):04X})  LLM {100 * lr:5.1f}%   "
                  f"real {100 * rr:.2f}%   human-fake {100 * fr:.2f}%")
    return flagged


def report_hygiene(gen):
    section("8. HYGIENE")
    t = gen.text.astype(str)
    print(f"  preamble leaks:      {t.str.contains(PREAMBLE_LEAK, case=False, regex=True).sum()}")
    print(f"  AI self-disclosure:  {t.str.contains(AI_DISCLOSURE, case=False, regex=True).sum()}")
    print(f"  exact duplicates:    {len(t) - t.nunique()}")
    print(f"  hotels used:         {gen.Category.nunique()} / {len(ExamplePool(cfg.DEFAULT_EXAMPLES_CSV).hotels)}")
    counts = gen.Category.value_counts()
    if len(counts) > 1:
        print(f"  per-hotel spread:    min={counts.min()} max={counts.max()}")


# ---------------------------------------------------------------------------

def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--generated", type=Path, default=cfg.DEFAULT_OUTPUT)
    p.add_argument("--examples-csv", type=Path, default=cfg.DEFAULT_EXAMPLES_CSV)
    p.add_argument("--host", default=cfg.DEFAULT_HOST)
    p.add_argument("--model", default=cfg.DEFAULT_MODEL, help="Model used for the judge")
    p.add_argument("--length-tolerance", type=float, default=cfg.DEFAULT_LENGTH_TOLERANCE)
    p.add_argument("--no-judge", action="store_true",
                   help="Skip the LLM sentiment judge (no Ollama needed)")
    args = p.parse_args(argv)

    if not args.generated.exists():
        sys.exit(f"No generated CSV at {args.generated}")

    gen = pd.read_csv(args.generated)
    hum = pd.read_csv(args.examples_csv)
    url = f"http://{args.host}{cfg.OLLAMA_CHAT_PATH}"

    print(f"Generated: {args.generated}  ({len(gen)} reviews, "
          f"{gen.cell_id.nunique()}/{len(ALL_CELLS)} cells)")
    print(f"Corpus:    {args.examples_csv}  ({len(hum)} human reviews)")

    recovered = reconstruct_instructions(gen, args.examples_csv, args.length_tolerance)

    report_length(gen, args.length_tolerance)
    report_sentiment(gen, url, args.model, use_judge=not args.no_judge)
    report_structure(gen, recovered)
    report_example_mode(gen, recovered)
    report_opener(gen, recovered)
    report_stylometry(gen, hum)
    flagged = report_perfect_separators(gen, hum)
    report_hygiene(gen)

    print()
    # Non-zero exit on a perfect separator: this is the failure mode that silently
    # invalidates the whole dataset, so it should break a pipeline, not just print.
    return 1 if flagged else 0


if __name__ == "__main__":
    sys.exit(main())
